/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as QueueImport } from './routes/queue'
import { Route as ConfImport } from './routes/conf'
import { Route as IndexImport } from './routes/index'

// Create/Update Routes

const QueueRoute = QueueImport.update({
  path: '/queue',
  getParentRoute: () => rootRoute,
} as any)

const ConfRoute = ConfImport.update({
  path: '/conf',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/conf': {
      id: '/conf'
      path: '/conf'
      fullPath: '/conf'
      preLoaderRoute: typeof ConfImport
      parentRoute: typeof rootRoute
    }
    '/queue': {
      id: '/queue'
      path: '/queue'
      fullPath: '/queue'
      preLoaderRoute: typeof QueueImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren({
  IndexRoute,
  ConfRoute,
  QueueRoute,
})

/* prettier-ignore-end */

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/conf",
        "/queue"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/conf": {
      "filePath": "conf.tsx"
    },
    "/queue": {
      "filePath": "queue.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
