// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetPreferences() {
  return window['go']['services']['ConfigService']['GetPreferences']();
}

export function GetWindowPosition(arg1) {
  return window['go']['services']['ConfigService']['GetWindowPosition'](arg1);
}

export function GetWindowSize() {
  return window['go']['services']['ConfigService']['GetWindowSize']();
}

export function SaveWindowPosition(arg1, arg2) {
  return window['go']['services']['ConfigService']['SaveWindowPosition'](arg1, arg2);
}

export function SaveWindowSize(arg1, arg2, arg3) {
  return window['go']['services']['ConfigService']['SaveWindowSize'](arg1, arg2, arg3);
}

export function SetPreferences(arg1) {
  return window['go']['services']['ConfigService']['SetPreferences'](arg1);
}
