// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {types} from '../models';
import {context} from '../models';

export function AddHotsTxt(arg1:string):Promise<types.JSResp>;

export function AddToQueue(arg1:string):Promise<types.JSResp>;

export function DeleteQueue(arg1:string):Promise<types.JSResp>;

export function GetAllQueue():Promise<types.JSResp>;

export function GetPaginatedQueue(arg1:types.Paginated):Promise<types.JSResp>;

export function Handle(arg1:context.Context):Promise<void>;

export function HandleClose():Promise<void>;

export function Search(arg1:string):Promise<types.JSResp>;

export function SearchWords(arg1:Array<string>):Promise<types.JSResp>;

export function Start():Promise<types.JSResp>;

export function Stop():Promise<types.JSResp>;
