// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddHotsTxt(arg1) {
  return window['go']['services']['CrawlerService']['AddHotsTxt'](arg1);
}

export function AddToQueue(arg1) {
  return window['go']['services']['CrawlerService']['AddToQueue'](arg1);
}

export function DeleteQueue(arg1) {
  return window['go']['services']['CrawlerService']['DeleteQueue'](arg1);
}

export function GetAllQueue() {
  return window['go']['services']['CrawlerService']['GetAllQueue']();
}

export function GetPaginatedQueue(arg1) {
  return window['go']['services']['CrawlerService']['GetPaginatedQueue'](arg1);
}

export function GetTreePages(arg1, arg2) {
  return window['go']['services']['CrawlerService']['GetTreePages'](arg1, arg2);
}

export function Handle(arg1) {
  return window['go']['services']['CrawlerService']['Handle'](arg1);
}

export function HandleClose() {
  return window['go']['services']['CrawlerService']['HandleClose']();
}

export function RemoveFromQueueByHost(arg1) {
  return window['go']['services']['CrawlerService']['RemoveFromQueueByHost'](arg1);
}

export function SearchWords(arg1) {
  return window['go']['services']['CrawlerService']['SearchWords'](arg1);
}

export function Start() {
  return window['go']['services']['CrawlerService']['Start']();
}

export function Stop() {
  return window['go']['services']['CrawlerService']['Stop']();
}
