// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddToQueue(arg1) {
  return window['go']['services']['CrawlingService']['AddToQueue'](arg1);
}

export function DeleteQueue(arg1) {
  return window['go']['services']['CrawlingService']['DeleteQueue'](arg1);
}

export function GetAllQueue() {
  return window['go']['services']['CrawlingService']['GetAllQueue']();
}

export function Search(arg1) {
  return window['go']['services']['CrawlingService']['Search'](arg1);
}

export function Start(arg1, arg2) {
  return window['go']['services']['CrawlingService']['Start'](arg1, arg2);
}
