// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddToQueue(arg1) {
  return window['go']['services']['CrawlerService']['AddToQueue'](arg1);
}

export function DeleteQueue(arg1) {
  return window['go']['services']['CrawlerService']['DeleteQueue'](arg1);
}

export function GetAllQueue() {
  return window['go']['services']['CrawlerService']['GetAllQueue']();
}

export function GetPaginatedQueue(arg1) {
  return window['go']['services']['CrawlerService']['GetPaginatedQueue'](arg1);
}

export function Handle(arg1) {
  return window['go']['services']['CrawlerService']['Handle'](arg1);
}

export function HandleClose() {
  return window['go']['services']['CrawlerService']['HandleClose']();
}

export function Search(arg1) {
  return window['go']['services']['CrawlerService']['Search'](arg1);
}

export function Start() {
  return window['go']['services']['CrawlerService']['Start']();
}

export function Stop() {
  return window['go']['services']['CrawlerService']['Stop']();
}
