// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {types} from '../models';
import {context} from '../models';
import {services} from '../models';

export function AddToQueue(arg1:string):Promise<types.JSResp>;

export function DeleteQueue(arg1:string):Promise<types.JSResp>;

export function GetAllQueue():Promise<types.JSResp>;

export function Search(arg1:string):Promise<types.JSResp>;

export function Start(arg1:context.Context,arg2:services.PreferencesService):Promise<void>;
