// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CheckForUpdate() {
  return window['go']['services']['PreferencesService']['CheckForUpdate']();
}

export function GetAppVersion() {
  return window['go']['services']['PreferencesService']['GetAppVersion']();
}

export function GetFontList() {
  return window['go']['services']['PreferencesService']['GetFontList']();
}

export function GetPreferences() {
  return window['go']['services']['PreferencesService']['GetPreferences']();
}

export function GetScanSize() {
  return window['go']['services']['PreferencesService']['GetScanSize']();
}

export function GetWindowPosition(arg1) {
  return window['go']['services']['PreferencesService']['GetWindowPosition'](arg1);
}

export function GetWindowSize() {
  return window['go']['services']['PreferencesService']['GetWindowSize']();
}

export function PreferenceWithContext(arg1) {
  return window['go']['services']['PreferencesService']['PreferenceWithContext'](arg1);
}

export function RestorePreferences() {
  return window['go']['services']['PreferencesService']['RestorePreferences']();
}

export function SaveWindowPosition(arg1, arg2) {
  return window['go']['services']['PreferencesService']['SaveWindowPosition'](arg1, arg2);
}

export function SaveWindowSize(arg1, arg2, arg3) {
  return window['go']['services']['PreferencesService']['SaveWindowSize'](arg1, arg2, arg3);
}

export function SetAppVersion(arg1) {
  return window['go']['services']['PreferencesService']['SetAppVersion'](arg1);
}

export function SetPreferences(arg1) {
  return window['go']['services']['PreferencesService']['SetPreferences'](arg1);
}

export function UpdatePreferences(arg1) {
  return window['go']['services']['PreferencesService']['UpdatePreferences'](arg1);
}
