// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Info() {
  return window['go']['services']['SystemService']['Info']();
}

export function Start(arg1, arg2) {
  return window['go']['services']['SystemService']['Start'](arg1, arg2);
}
