// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {types} from '../models';
import {options} from '../models';
import {context} from '../models';

export function CheckForUpdate():Promise<types.JSResp>;

export function Info():Promise<types.JSResp>;

export function OnSecondInstanceLaunch(arg1:options.SecondInstanceData):Promise<void>;

export function Start(arg1:context.Context,arg2:string,arg3:string):Promise<void>;
