// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CheckForUpdate() {
  return window['go']['services']['SystemService']['CheckForUpdate']();
}

export function ExportData() {
  return window['go']['services']['SystemService']['ExportData']();
}

export function ExportQueue() {
  return window['go']['services']['SystemService']['ExportQueue']();
}

export function ImportData() {
  return window['go']['services']['SystemService']['ImportData']();
}

export function ImportQueue() {
  return window['go']['services']['SystemService']['ImportQueue']();
}

export function Info() {
  return window['go']['services']['SystemService']['Info']();
}

export function OnSecondInstanceLaunch(arg1) {
  return window['go']['services']['SystemService']['OnSecondInstanceLaunch'](arg1);
}

export function Start(arg1, arg2, arg3, arg4) {
  return window['go']['services']['SystemService']['Start'](arg1, arg2, arg3, arg4);
}
