// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CheckForUpdate() {
  return window['go']['services']['SystemService']['CheckForUpdate']();
}

export function Info() {
  return window['go']['services']['SystemService']['Info']();
}

export function OnSecondInstanceLaunch(arg1) {
  return window['go']['services']['SystemService']['OnSecondInstanceLaunch'](arg1);
}

export function Start(arg1, arg2, arg3) {
  return window['go']['services']['SystemService']['Start'](arg1, arg2, arg3);
}
